<?xml version="1.0"?>
<robot name="hokuyo_sensor" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Hokuyo Laser scanner -->
    <xacro:property name="hokuyo_size" value="0.05" />

    <xacro:macro name="hokuyo" params="base_radius base_height">
        <link name="hokuyo_link">
            <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
            </geometry>
            <material name="Blue" />
            </visual>
        </link>
        <joint name="hokuyo_joint" type="fixed">
            <origin xyz="${base_radius - hokuyo_size/2} 0 ${base_height+hokuyo_size/4}" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="hokuyo_link" />
        </joint>
        <gazebo reference="hokuyo_link">
            <material>Gazebo/Blue</material>
            <turnGravityOff>false</turnGravityOff>
            <sensor type="ray" name="head_hokuyo_sensor">
            <pose>${hokuyo_size/2} 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>720</samples>
                    <resolution>1</resolution>
                    <min_angle>-1.570796</min_angle>
                    <max_angle>1.570796</max_angle>
                </horizontal>
                </scan>
                <range>
                <min>0.10</min>
                <max>10.0</max>
                <resolution>0.001</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>hokuyo_link</frameName>
            </plugin>
            </sensor>
        </gazebo>
  </xacro:macro>
</robot>